
services:
  web:
    build: .
    container_name: django_web
    command: gunicorn web_scraping.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: elcomercio_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: django
      MYSQL_PASSWORD: djangopass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A web_scraping worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A web_scraping beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  mysql_data: